/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rateLimit.proto */

#ifndef PROTOBUF_C_rateLimit_2eproto__INCLUDED
#define PROTOBUF_C_rateLimit_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RateLimitValues RateLimitValues;
typedef struct RateLimitResponse RateLimitResponse;


/* --- enums --- */


/* --- messages --- */

struct  RateLimitValues
{
  ProtobufCMessage base;
  ProtobufCBinaryData key;
  uint64_t excess;
  uint64_t last;
};
#define RATE_LIMIT_VALUES__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rate_limit_values__descriptor) \
    , {0,NULL}, 0, 0 }


struct  RateLimitResponse
{
  ProtobufCMessage base;
  size_t n_ratelimits;
  RateLimitValues **ratelimits;
};
#define RATE_LIMIT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&rate_limit_response__descriptor) \
    , 0,NULL }


/* RateLimitValues methods */
void   rate_limit_values__init
                     (RateLimitValues         *message);
size_t rate_limit_values__get_packed_size
                     (const RateLimitValues   *message);
size_t rate_limit_values__pack
                     (const RateLimitValues   *message,
                      uint8_t             *out);
size_t rate_limit_values__pack_to_buffer
                     (const RateLimitValues   *message,
                      ProtobufCBuffer     *buffer);
RateLimitValues *
       rate_limit_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rate_limit_values__free_unpacked
                     (RateLimitValues *message,
                      ProtobufCAllocator *allocator);
/* RateLimitResponse methods */
void   rate_limit_response__init
                     (RateLimitResponse         *message);
size_t rate_limit_response__get_packed_size
                     (const RateLimitResponse   *message);
size_t rate_limit_response__pack
                     (const RateLimitResponse   *message,
                      uint8_t             *out);
size_t rate_limit_response__pack_to_buffer
                     (const RateLimitResponse   *message,
                      ProtobufCBuffer     *buffer);
RateLimitResponse *
       rate_limit_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   rate_limit_response__free_unpacked
                     (RateLimitResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RateLimitValues_Closure)
                 (const RateLimitValues *message,
                  void *closure_data);
typedef void (*RateLimitResponse_Closure)
                 (const RateLimitResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor rate_limit_values__descriptor;
extern const ProtobufCMessageDescriptor rate_limit_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_rateLimit_2eproto__INCLUDED */
