/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: rateLimit.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "rateLimit.pb-c.h"
void   rate_limit_values__init
                     (RateLimitValues         *message)
{
  static const RateLimitValues init_value = RATE_LIMIT_VALUES__INIT;
  *message = init_value;
}
size_t rate_limit_values__get_packed_size
                     (const RateLimitValues *message)
{
  assert(message->base.descriptor == &rate_limit_values__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rate_limit_values__pack
                     (const RateLimitValues *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rate_limit_values__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rate_limit_values__pack_to_buffer
                     (const RateLimitValues *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rate_limit_values__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RateLimitValues *
       rate_limit_values__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RateLimitValues *)
     protobuf_c_message_unpack (&rate_limit_values__descriptor,
                                allocator, len, data);
}
void   rate_limit_values__free_unpacked
                     (RateLimitValues *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rate_limit_values__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   rate_limit_response__init
                     (RateLimitResponse         *message)
{
  static const RateLimitResponse init_value = RATE_LIMIT_RESPONSE__INIT;
  *message = init_value;
}
size_t rate_limit_response__get_packed_size
                     (const RateLimitResponse *message)
{
  assert(message->base.descriptor == &rate_limit_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t rate_limit_response__pack
                     (const RateLimitResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &rate_limit_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t rate_limit_response__pack_to_buffer
                     (const RateLimitResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &rate_limit_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
RateLimitResponse *
       rate_limit_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (RateLimitResponse *)
     protobuf_c_message_unpack (&rate_limit_response__descriptor,
                                allocator, len, data);
}
void   rate_limit_response__free_unpacked
                     (RateLimitResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &rate_limit_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor rate_limit_values__field_descriptors[3] =
{
  {
    "key",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(RateLimitValues, key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "excess",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RateLimitValues, excess),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "last",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(RateLimitValues, last),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rate_limit_values__field_indices_by_name[] = {
  1,   /* field[1] = excess */
  0,   /* field[0] = key */
  2,   /* field[2] = last */
};
static const ProtobufCIntRange rate_limit_values__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor rate_limit_values__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RateLimitValues",
  "RateLimitValues",
  "RateLimitValues",
  "",
  sizeof(RateLimitValues),
  3,
  rate_limit_values__field_descriptors,
  rate_limit_values__field_indices_by_name,
  1,  rate_limit_values__number_ranges,
  (ProtobufCMessageInit) rate_limit_values__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor rate_limit_response__field_descriptors[1] =
{
  {
    "rateLimits",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(RateLimitResponse, n_ratelimits),
    offsetof(RateLimitResponse, ratelimits),
    &rate_limit_values__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned rate_limit_response__field_indices_by_name[] = {
  0,   /* field[0] = rateLimits */
};
static const ProtobufCIntRange rate_limit_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor rate_limit_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "RateLimitResponse",
  "RateLimitResponse",
  "RateLimitResponse",
  "",
  sizeof(RateLimitResponse),
  1,
  rate_limit_response__field_descriptors,
  rate_limit_response__field_indices_by_name,
  1,  rate_limit_response__number_ranges,
  (ProtobufCMessageInit) rate_limit_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
